# Generated by Django 3.1.3 on 2020-11-15 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_administrador_comensal_locatario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('prom_califi', models.IntegerField(default=0)),
                ('ruta_fotos', models.CharField(max_length=100)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('valor', models.IntegerField(default=0)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resenhas',
            fields=[
                ('id_resenhas', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=500)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.local')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=250)),
                ('valor', models.IntegerField(default=0)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.local')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_califi', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField(default=0)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.local')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.usuario')),
            ],
        ),
    ]
