# Generated by Django 3.1.3 on 2020-11-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_calificacion_local_menu_planes_resenhas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasenha',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
