# Generated by Django 3.1.3 on 2020-12-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20201207_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comensal',
            name='username',
        ),
        migrations.RemoveField(
            model_name='locatario',
            name='Username',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Comensal',
        ),
        migrations.DeleteModel(
            name='Locatario',
        ),
    ]
