# Generated by Django 3.1.3 on 2020-12-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20201208_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nom_usuario', models.CharField(max_length=20)),
                ('contrasenha', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=1)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.estado')),
            ],
        ),
        migrations.AlterField(
            model_name='administrador',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.usuario'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.usuario'),
        ),
        migrations.AlterField(
            model_name='comensal',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.usuario'),
        ),
        migrations.AlterField(
            model_name='locatario',
            name='Usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.usuario'),
        ),
        migrations.AlterField(
            model_name='resenhas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.usuario'),
        ),
        migrations.DeleteModel(
            name='Userr',
        ),
    ]
