# Generated by Django 3.1.3 on 2020-12-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_auto_20201209_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='tipo',
        ),
    ]
