# Generated by Django 3.1.3 on 2020-12-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_remove_perfil_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
